# Generated by Django 5.0.1 on 2024-09-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vuelos',
            fields=[
                ('idVuelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=15)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
